ALTER TABLE IF EXISTS profiles ADD COLUMN IF NOT EXISTS skills TEXT[] DEFAULT '{}';
ALTER TABLE IF EXISTS profiles ADD COLUMN IF NOT EXISTS reputation_score FLOAT DEFAULT 0.0;
ALTER TABLE IF EXISTS profiles ADD COLUMN IF NOT EXISTS follower_count INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS profiles ADD COLUMN IF NOT EXISTS project_count INTEGER DEFAULT 0;

ALTER TABLE IF EXISTS posts ADD COLUMN IF NOT EXISTS hot_score FLOAT DEFAULT 0.0;
ALTER TABLE IF EXISTS posts ADD COLUMN IF NOT EXISTS search_vector TSVECTOR;
ALTER TABLE IF EXISTS posts ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';

ALTER TABLE IF EXISTS jobs ADD COLUMN IF NOT EXISTS hot_score FLOAT DEFAULT 0.0;
ALTER TABLE IF EXISTS jobs ADD COLUMN IF NOT EXISTS search_vector TSVECTOR;
ALTER TABLE IF EXISTS jobs ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
ALTER TABLE IF EXISTS jobs ADD COLUMN IF NOT EXISTS view_count INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS jobs ADD COLUMN IF NOT EXISTS application_count INTEGER DEFAULT 0;

ALTER TABLE IF EXISTS experiences ADD COLUMN IF NOT EXISTS skills_used TEXT[] DEFAULT '{}';
ALTER TABLE IF EXISTS experiences ADD COLUMN IF NOT EXISTS duration_months INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS experiences ADD COLUMN IF NOT EXISTS company_id UUID;
ALTER TABLE IF EXISTS experiences ADD COLUMN IF NOT EXISTS salary_amount NUMERIC;
ALTER TABLE IF EXISTS experiences ADD COLUMN IF NOT EXISTS currency VARCHAR(3) DEFAULT 'EUR';

ALTER TABLE IF EXISTS educations ADD COLUMN IF NOT EXISTS skills_acquired TEXT[] DEFAULT '{}';

ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS hot_score FLOAT DEFAULT 0.0;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS search_vector TSVECTOR;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS view_count INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS like_count INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS projects ADD COLUMN IF NOT EXISTS comment_count INTEGER DEFAULT 0;
