-- Creation of industries table
CREATE TABLE IF NOT EXISTS industries (
    id VARCHAR(100) PRIMARY KEY,
    label VARCHAR(255) NOT NULL,
    icon VARCHAR(100) NOT NULL,
    category VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add industry_id to users
ALTER TABLE users ADD COLUMN IF NOT EXISTS industry_id VARCHAR(100) REFERENCES industries(id);

-- Seed data
INSERT INTO industries (id, label, icon, category) VALUES
('software_eng', 'Ingénierie Logicielle', 'Cpu', 'DEVELOPMENT & ENGINEERING'),
('web_dev', 'Développement Web (Front, Back, Fullstack)', 'Cpu', 'DEVELOPMENT & ENGINEERING'),
('mobile_dev', 'Développement d''Apps Mobiles (iOS, Android)', 'Cpu', 'DEVELOPMENT & ENGINEERING'),
('devops_cloud', 'DevOps et Architecture Cloud', 'Cpu', 'DEVELOPMENT & ENGINEERING'),
('game_development', 'Développement de Jeux Vidéo', 'Palette', 'DEVELOPMENT & ENGINEERING'),
('embedded_systems', 'Systèmes Embarqués et IOT', 'Cpu', 'DEVELOPMENT & ENGINEERING'),
('it_services_consulting', 'Services et conseil technologiques (ESN)', 'Cpu', 'TECH & INNOVATION'),
('software_dev', 'Édition de logiciels et SaaS', 'Cpu', 'TECH & INNOVATION'),
('cybersecurity', 'Cybersécurité', 'Cpu', 'TECH & INNOVATION'),
('ai_data', 'Intelligence Artificielle et Data Science', 'Cpu', 'TECH & INNOVATION'),
('cloud_infra', 'Infrastructure Cloud et Réseaux', 'Cpu', 'TECH & INNOVATION'),
('ecommerce', 'E-commerce et Vente en ligne', 'Building2', 'TECH & INNOVATION'),
('gaming', 'Jeux Vidéo et Divertissement Numérique', 'Palette', 'TECH & INNOVATION'),
('hardware_semiconductors', 'Matériel informatique et semi-conducteurs', 'Cpu', 'TECH & INNOVATION'),
('biotech', 'Biotechnologie', 'Stethoscope', 'TECH & INNOVATION'),
('robotics', 'Robotique et Automatisation', 'Cpu', 'TECH & INNOVATION'),
('blockhain_crypto', 'Blockchain et Crypto-actifs', 'BriefcaseBusiness', 'TECH & INNOVATION'),
('iot', 'Objets Connectés (IoT)', 'Cpu', 'TECH & INNOVATION'),
('banking', 'Banque et Services financiers', 'BriefcaseBusiness', 'FINANCE & LEGAL'),
('insurance', 'Assurance', 'BriefcaseBusiness', 'FINANCE & LEGAL'),
('fintech', 'Fintech', 'BriefcaseBusiness', 'FINANCE & LEGAL'),
('audit_accounting', 'Comptabilité et Audit', 'BriefcaseBusiness', 'FINANCE & LEGAL'),
('investment_vc', 'Capital-risque et Investissement', 'BriefcaseBusiness', 'FINANCE & LEGAL'),
('trading', 'Marchés boursiers et Trading', 'BriefcaseBusiness', 'FINANCE & LEGAL'),
('law_firm', 'Cabinets d''avocats et Juridique', 'Scale', 'FINANCE & LEGAL'),
('notary', 'Notariat', 'Scale', 'FINANCE & LEGAL'),
('intellectual_property', 'Propriété Intellectuelle', 'Scale', 'FINANCE & LEGAL'),
('hospitals', 'Santé, Hôpitaux et Cliniques', 'Stethoscope', 'HEALTH & WELLNESS'),
('pharmaceuticals', 'Industrie Pharmaceutique', 'Stethoscope', 'HEALTH & WELLNESS'),
('medical_devices', 'Dispositifs Médicaux', 'Stethoscope', 'HEALTH & WELLNESS'),
('wellness_fitness', 'Bien-être et Fitness', 'Stethoscope', 'HEALTH & WELLNESS'),
('veterinary', 'Services Vétérinaires', 'Stethoscope', 'HEALTH & WELLNESS'),
('psychology', 'Santé Mentale et Psychologie', 'Stethoscope', 'HEALTH & WELLNESS'),
('higher_education', 'Enseignement Supérieur et Recherche', 'GraduationCap', 'EDUCATION & HUMAN RESOURCES'),
('elearning', 'E-learning et Formation en ligne', 'GraduationCap', 'EDUCATION & HUMAN RESOURCES'),
('k12_education', 'Écoles et Éducation Primaire/Secondaire', 'GraduationCap', 'EDUCATION & HUMAN RESOURCES'),
('hr_recruitment', 'Ressources Humaines et Recrutement', 'BriefcaseBusiness', 'EDUCATION & HUMAN RESOURCES'),
('coaching_mentoring', 'Coaching et Accompagnement', 'GraduationCap', 'EDUCATION & HUMAN RESOURCES'),
('advertising_marketing', 'Publicité et Marketing Digital', 'Building2', 'MARKETING & CREATIVE'),
('pr_comm', 'Relations Publiques et Communication', 'Building2', 'MARKETING & CREATIVE'),
('design_agencies', 'Agences de Design et Création', 'Palette', 'MARKETING & CREATIVE'),
('architecture_interior', 'Architecture et Décoration d''intérieur', 'Palette', 'MARKETING & CREATIVE'),
('fashion_luxury', 'Mode et Luxe', 'Palette', 'MARKETING & CREATIVE'),
('photography_video', 'Photographie et Production Audiovisuelle', 'Palette', 'MARKETING & CREATIVE'),
('music_performing_arts', 'Musique et Arts du spectacle', 'Palette', 'MARKETING & CREATIVE'),
('journalism_publishing', 'Journalisme et Édition', 'Palette', 'MARKETING & CREATIVE'),
('real_estate_services', 'Immobilier (Vente et Gestion)', 'Building2', 'REAL ESTATE & CONSTRUCTION'),
('construction_civil_eng', 'BTP et Génie Civil', 'Building2', 'REAL ESTATE & CONSTRUCTION'),
('urban_planning', 'Urbanisme et Aménagement', 'Building2', 'REAL ESTATE & CONSTRUCTION'),
('automotive', 'Industrie Automobile', 'Building2', 'INDUSTRIAL & ENERGY'),
('aerospace_defense', 'Aéronautique, Espace et Défense', 'Building2', 'INDUSTRIAL & ENERGY'),
('energy_utilities', 'Énergie, Électricité et Eau', 'Building2', 'INDUSTRIAL & ENERGY'),
('oil_gas', 'Pétrole et Gaz', 'Building2', 'INDUSTRIAL & ENERGY'),
('renewable_energy', 'Énergies Renouvelables', 'Building2', 'INDUSTRIAL & ENERGY'),
('manufacturing_goods', 'Manufacture et Produits de consommation', 'Building2', 'INDUSTRIAL & ENERGY'),
('chemicals', 'Industrie Chimique', 'Building2', 'INDUSTRIAL & ENERGY'),
('logistics_supply_chain', 'Logistique et Supply Chain', 'Building2', 'INDUSTRIAL & ENERGY'),
('maritime', 'Transport Maritime et Ports', 'Building2', 'INDUSTRIAL & ENERGY'),
('retail_dist', 'Commerce de détail et Distribution', 'Building2', 'CONSUMER SERVICES'),
('hospitality_tourism', 'Hôtellerie et Tourisme', 'Building2', 'CONSUMER SERVICES'),
('restaurants_fnb', 'Restauration et Agroalimentaire', 'Building2', 'CONSUMER SERVICES'),
('events_planning', 'Événementiel', 'Building2', 'CONSUMER SERVICES'),
('sports_recreation', 'Sports et Loisirs', 'Building2', 'CONSUMER SERVICES'),
('beauty_cosmetics', 'Beauté et Cosmétiques', 'Palette', 'CONSUMER SERVICES'),
('customer_service_outsourcing', 'Relation Client et Outsourcing', 'Building2', 'CONSUMER SERVICES'),
('non_profit_ngo', 'ONG et Associations caritatives', 'Building2', 'PUBLIC & SOCIAL'),
('government_admin', 'Administration Publique', 'Scale', 'PUBLIC & SOCIAL'),
('politics_lobbying', 'Politique et Lobbying', 'Scale', 'PUBLIC & SOCIAL'),
('international_affairs', 'Affaires Internationales et Diplomatie', 'Scale', 'PUBLIC & SOCIAL'),
('environmental_services', 'Environnement et Développement Durable', 'Building2', 'PUBLIC & SOCIAL'),
('strategy_consulting', 'Conseil en Stratégie', 'BriefcaseBusiness', 'SPECIALIZED SERVICES'),
('translation_linguistics', 'Traduction et Services Linguistiques', 'Palette', 'SPECIALIZED SERVICES'),
('security_investigation', 'Sécurité et Investigations', 'Scale', 'SPECIALIZED SERVICES'),
('facilities_mgt', 'Services aux Entreprises (Facilities Mgt)', 'Building2', 'SPECIALIZED SERVICES'),
('waste_mgt', 'Gestion des Déchets et Recyclage', 'Building2', 'SPECIALIZED SERVICES'),
('agribusiness_farming', 'Agriculture et Agrobusiness', 'Building2', 'OTHER'),
('mining_metals', 'Mines et Métallurgie', 'Building2', 'OTHER'),
('textiles_apparel', 'Textile et Habillement', 'Palette', 'OTHER'),
('other_industry', 'Autre secteur', 'Building2', 'OTHER')
ON CONFLICT (id) DO UPDATE SET 
    label = EXCLUDED.label,
    icon = EXCLUDED.icon,
    category = EXCLUDED.category;
